data_folder = "/app/data/"
max_upload_size = 104857600
database_type = "postgresql"
database_connection_url = "host=db port=5432 user=postgres password=123 database=imagehost sslmode=disable"
port = "80"
behind_reverse_proxy = false
trusted_proxy = ""
branding = "Docker Example"